version: "3.5"
services:
  mysql:
    image: mysql:latest
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    #user: ${LOCAL_USER}
    volumes:
      - .:/var/www/symfony
      - /tmp:/tmp

  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    depends_on:
      - php
    volumes:
      - ./public:/var/www/symfony/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - ${NGINX_PORT}:80

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - ${ADMINER_PORT}:8080

  webgrind:
    image: wodby/webgrind
    restart: on-failure
    volumes:
      - /tmp:/tmp
      - .:/var/www/symfony
    ports:
      - ${WEBGRIND_PORT}:8080
