version: "3.5"
services:
  php:
    volumes:
      - .:/var/www/symfony

  nginx:
    volumes:
      - ./public:/var/www/symfony/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - ${NGINX_PORT}:80

  adminer:
    ports:
      - ${ADMINER_PORT}:8080
