version: "3.5"
services:
  mysql:
    image: mysql:5.7
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      TZ: ${TZ}

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        TZ: ${TZ}
        LOCAL_USER: ${LOCAL_USER}
    restart: on-failure
    user: ${LOCAL_USER}
    volumes:
      - .:/var/www/symfony
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
      - tmp:/tmp/xdebug

  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    depends_on:
      - php
    volumes:
      - ./public:/var/www/symfony/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - ${NGINX_PORT}:80

  adminer:
    image: adminer
    restart: on-failure
    depends_on:
      - mysql
    ports:
      - ${ADMINER_PORT}:8080

  webgrind:
    image: wodby/webgrind
    restart: on-failure
    user: ${LOCAL_USER}
    environment:
      TZ: ${TZ}
      WEBGRIND_DEFAULT_TIMEZONE: ${TZ}
    volumes:
      - tmp:/tmp
      - .:/var/www/symfony
    ports:
      - ${WEBGRIND_PORT}:8080

volumes:
  tmp:
  mysql: